/////// content type must come one line after the post if no the req.body will be null!

@host=http://localhost:3000
@token1=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IkV0YWkiLCJ1c2VySWQiOiI2NzNhMTYwZGE2Y2MyZDBjZTMwZmFhMzIiLCJpYXQiOjE3MzE4NjA4NDB9.faDOPT-eG3XACQ6SpxdeGrgKCDZli7jwCZLJqvIdHWY
@token2=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IkRhbmllbCIsInVzZXJJZCI6IjY3M2ExZTE2ZThhZGNmOWE0MzVlNThlZCIsImlhdCI6MTczMTg2MjA5Mn0.fAXrzFTP8n2TVbUd2pe4cCWSBio_OLBl0685GJCUciQ
@player1="Etai"
@player2="Daniel"
@player2WithoutQuoutes=Daniel

@user1id=673a160da6cc2d0ce30faa32
@user2id=673a1e16e8adcf9a435e58ed

@user1idasString="673a160da6cc2d0ce30faa32"
@user2idasString="673a1e16e8adcf9a435e58ed"

@gameid=673a1e88e8adcf9a435e58f4
get http://localhost:3000/

###
POST {{host}}/users/register/
Content-Type: application/json

{
    "userName":{{player2}},
      "password":"abc"
}
###

post {{host}}/users/login/
Content-Type: application/json

{
    "userName":{{player2}},
      "password":"abc"
}


###
GET {{host}}/users/{{user2id}}/stats/
Authorization: Bearer {{token2}}



###
// i'm making it as i need to verify the jwt of player 1. i,e player 1 want to crate the gmae
#TODO: untill we dont have websockets i dont need this endpoint
post {{host}}/games/create
Authorization: Bearer {{token1}}
Content-Type: application/json

{
        "player1" : {{player1}},
        "player2": {{player2}}
}

###
#TODO: untill we dont have websockets i dont need this endpoint
//this route is to update the score a single game given by the game id param
put {{host}}/games/{{gameid}}
Authorization: Bearer {{token1}}
Content-Type: application/json

{
        "player1Score" : 2,
        "player2Score": 5
}
###


get {{host}}/games/history
Authorization: Bearer {{token1}}
###


### 
post {{host}}/games/stats
Content-Type: application/json

{
  "max_hits_in_game": 11,
  "average_hits_in_game": 7,
  "player_left": {
    "name": {{user1idasString}},
    "faults": [1, 1, 1],
    "aces": 0,
    "average_speed": 0,
    "depth_of_hits": [0, 0, 1, 1, 1, 10, 2, 0]
  },
  "player_right": {
    "name": {{user2idasString}},
    "faults": [0, 1, 0],
    "aces": 0,
    "average_speed": 0,
    "depth_of_hits": [0, 1, 1, 1, 1, 5, 5, 1]
  }
}

###
//! gameid is a path parms 
get {{host}}/games/{{gameid}}
Authorization: Bearer {{token1}}
####











###
get {{host}}/games//history/against-player?player_name={{player2WithoutQuoutes}}
Authorization: Bearer {{token1}}
####



###
# {
#     "scores": {
#         "player1": {{player1}},
#         "player1Score": 21,
#         "player2": {{player2}},
#         "player2Score": 15
#     },
#     "datePlayed": "2024-10-12T18:30:00Z",
#     "video": {
#         "title": "Game 1 - Summer Open Championship",
#         "url": "https://example.com/videos/game1.mp4",
#         "duration": 360
#     }
# }





















